//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;


// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/CartaPorte30", IsNullable = false)]
public partial class CartaPorte
{

    private CartaPorteUbicacion[] ubicacionesField;

    private CartaPorteMercancias mercanciasField;

    private CartaPorteTiposFigura[] figuraTransporteField;

    private string versionField;

    private string idCCPField;

    private string transpInternacField;

    private string regimenAduaneroField;

    private bool regimenAduaneroFieldSpecified;

    private string entradaSalidaMercField;

    private bool entradaSalidaMercFieldSpecified;

    private string paisOrigenDestinoField;

    private bool paisOrigenDestinoFieldSpecified;

    private string viaEntradaSalidaField;

    private bool viaEntradaSalidaFieldSpecified;

    private decimal totalDistRecField;

    private bool totalDistRecFieldSpecified;

    private string registroISTMOField;

    private bool registroISTMOFieldSpecified;

    private string ubicacionPoloOrigenField;

    private bool ubicacionPoloOrigenFieldSpecified;

    private string ubicacionPoloDestinoField;

    private bool ubicacionPoloDestinoFieldSpecified;

    public CartaPorte()
    {
        this.versionField = "3.0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Ubicacion", IsNullable = false)]
    public CartaPorteUbicacion[] Ubicaciones
    {
        get
        {
            return this.ubicacionesField;
        }
        set
        {
            this.ubicacionesField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercancias Mercancias
    {
        get
        {
            return this.mercanciasField;
        }
        set
        {
            this.mercanciasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("TiposFigura", IsNullable = false)]
    public CartaPorteTiposFigura[] FiguraTransporte
    {
        get
        {
            return this.figuraTransporteField;
        }
        set
        {
            this.figuraTransporteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IdCCP
    {
        get
        {
            return this.idCCPField;
        }
        set
        {
            this.idCCPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TranspInternac
    {
        get
        {
            return this.transpInternacField;
        }
        set
        {
            this.transpInternacField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RegimenAduanero
    {
        get
        {
            return this.regimenAduaneroField;
        }
        set
        {
            regimenAduaneroFieldSpecified = true;
            this.regimenAduaneroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RegimenAduaneroSpecified
    {
        get
        {
            return this.regimenAduaneroFieldSpecified;
        }
        set
        {
            this.regimenAduaneroFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EntradaSalidaMerc
    {
        get
        {
            return this.entradaSalidaMercField;
        }
        set
        {
            entradaSalidaMercFieldSpecified = true;
            this.entradaSalidaMercField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntradaSalidaMercSpecified
    {
        get
        {
            return this.entradaSalidaMercFieldSpecified;
        }
        set
        {
            this.entradaSalidaMercFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PaisOrigenDestino
    {
        get
        {
            return this.paisOrigenDestinoField;
        }
        set
        {
            paisOrigenDestinoFieldSpecified = true;
            this.paisOrigenDestinoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PaisOrigenDestinoSpecified
    {
        get
        {
            return this.paisOrigenDestinoFieldSpecified;
        }
        set
        {
            this.paisOrigenDestinoFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ViaEntradaSalida
    {
        get
        {
            return this.viaEntradaSalidaField;
        }
        set
        {
            viaEntradaSalidaFieldSpecified = true;
            this.viaEntradaSalidaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ViaEntradaSalidaSpecified
    {
        get
        {
            return this.viaEntradaSalidaFieldSpecified;
        }
        set
        {
            this.viaEntradaSalidaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal TotalDistRec
    {
        get
        {
            return this.totalDistRecField;
        }
        set
        {
            totalDistRecFieldSpecified = true;
            this.totalDistRecField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalDistRecSpecified
    {
        get
        {
            return this.totalDistRecFieldSpecified;
        }
        set
        {
            this.totalDistRecFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RegistroISTMO
    {
        get
        {
            return this.registroISTMOField;
        }
        set
        {
            registroISTMOFieldSpecified = true;
            this.registroISTMOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RegistroISTMOSpecified
    {
        get
        {
            return this.registroISTMOFieldSpecified;
        }
        set
        {
            this.registroISTMOFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UbicacionPoloOrigen
    {
        get
        {
            return this.ubicacionPoloOrigenField;
        }
        set
        {
            ubicacionPoloOrigenFieldSpecified = true;
            this.ubicacionPoloOrigenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UbicacionPoloOrigenSpecified
    {
        get
        {
            return this.ubicacionPoloOrigenFieldSpecified;
        }
        set
        {
            this.ubicacionPoloOrigenFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UbicacionPoloDestino
    {
        get
        {
            return this.ubicacionPoloDestinoField;
        }
        set
        {
            ubicacionPoloDestinoFieldSpecified = true;
            this.ubicacionPoloDestinoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UbicacionPoloDestinoSpecified
    {
        get
        {
            return this.ubicacionPoloDestinoFieldSpecified;
        }
        set
        {
            this.ubicacionPoloDestinoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteUbicacion
{

    private CartaPorteUbicacionDomicilio domicilioField;

    private string tipoUbicacionField;

    private string iDUbicacionField;

    private string rFCRemitenteDestinatarioField;

    private string nombreRemitenteDestinatarioField;

    private string numRegIdTribField;

    private string residenciaFiscalField;

    private bool residenciaFiscalFieldSpecified;

    private string numEstacionField;

    private bool numEstacionFieldSpecified;

    private string nombreEstacionField;

    private string navegacionTraficoField;

    private bool navegacionTraficoFieldSpecified;

    private System.DateTime fechaHoraSalidaLlegadaField;

    private string tipoEstacionField;

    private bool tipoEstacionFieldSpecified;

    private decimal distanciaRecorridaField;

    private bool distanciaRecorridaFieldSpecified;

    /// <remarks/>
    public CartaPorteUbicacionDomicilio Domicilio
    {
        get
        {
            return this.domicilioField;
        }
        set
        {
            this.domicilioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoUbicacion
    {
        get
        {
            return this.tipoUbicacionField;
        }
        set
        {
            this.tipoUbicacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IDUbicacion
    {
        get
        {
            return this.iDUbicacionField;
        }
        set
        {
            this.iDUbicacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RFCRemitenteDestinatario
    {
        get
        {
            return this.rFCRemitenteDestinatarioField;
        }
        set
        {
            this.rFCRemitenteDestinatarioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreRemitenteDestinatario
    {
        get
        {
            return this.nombreRemitenteDestinatarioField;
        }
        set
        {
            this.nombreRemitenteDestinatarioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumRegIdTrib
    {
        get
        {
            return this.numRegIdTribField;
        }
        set
        {
            this.numRegIdTribField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResidenciaFiscal
    {
        get
        {
            return this.residenciaFiscalField;
        }
        set
        {
            residenciaFiscalFieldSpecified = true;
            this.residenciaFiscalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResidenciaFiscalSpecified
    {
        get
        {
            return this.residenciaFiscalFieldSpecified;
        }
        set
        {
            this.residenciaFiscalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumEstacion
    {
        get
        {
            return this.numEstacionField;
        }
        set
        {
            numEstacionFieldSpecified = true;
            this.numEstacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumEstacionSpecified
    {
        get
        {
            return this.numEstacionFieldSpecified;
        }
        set
        {
            this.numEstacionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreEstacion
    {
        get
        {
            return this.nombreEstacionField;
        }
        set
        {
            this.nombreEstacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NavegacionTrafico
    {
        get
        {
            return this.navegacionTraficoField;
        }
        set
        {
            navegacionTraficoFieldSpecified = true;
            this.navegacionTraficoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NavegacionTraficoSpecified
    {
        get
        {
            return this.navegacionTraficoFieldSpecified;
        }
        set
        {
            this.navegacionTraficoFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime FechaHoraSalidaLlegada
    {
        get
        {
            return this.fechaHoraSalidaLlegadaField;
        }
        set
        {
            this.fechaHoraSalidaLlegadaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoEstacion
    {
        get
        {
            return this.tipoEstacionField;
        }
        set
        {
            tipoEstacionFieldSpecified = true;
            this.tipoEstacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TipoEstacionSpecified
    {
        get
        {
            return this.tipoEstacionFieldSpecified;
        }
        set
        {
            this.tipoEstacionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal DistanciaRecorrida
    {
        get
        {
            return this.distanciaRecorridaField;
        }
        set
        {
            distanciaRecorridaFieldSpecified = true;
            this.distanciaRecorridaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DistanciaRecorridaSpecified
    {
        get
        {
            return this.distanciaRecorridaFieldSpecified;
        }
        set
        {
            this.distanciaRecorridaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteUbicacionDomicilio
{

    private string calleField;

    private string numeroExteriorField;

    private string numeroInteriorField;

    private string coloniaField;

    private string localidadField;

    private string referenciaField;

    private string municipioField;

    private string estadoField;

    private string paisField;

    private string codigoPostalField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Calle
    {
        get
        {
            return this.calleField;
        }
        set
        {
            this.calleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroExterior
    {
        get
        {
            return this.numeroExteriorField;
        }
        set
        {
            this.numeroExteriorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroInterior
    {
        get
        {
            return this.numeroInteriorField;
        }
        set
        {
            this.numeroInteriorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Colonia
    {
        get
        {
            return this.coloniaField;
        }
        set
        {
            this.coloniaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Localidad
    {
        get
        {
            return this.localidadField;
        }
        set
        {
            this.localidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Referencia
    {
        get
        {
            return this.referenciaField;
        }
        set
        {
            this.referenciaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Municipio
    {
        get
        {
            return this.municipioField;
        }
        set
        {
            this.municipioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Estado
    {
        get
        {
            return this.estadoField;
        }
        set
        {
            this.estadoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Pais
    {
        get
        {
            return this.paisField;
        }
        set
        {
            this.paisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CodigoPostal
    {
        get
        {
            return this.codigoPostalField;
        }
        set
        {
            this.codigoPostalField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercancias
{

    private CartaPorteMercanciasMercancia[] mercanciaField;

    private CartaPorteMercanciasAutotransporte autotransporteField;

    private CartaPorteMercanciasTransporteMaritimo transporteMaritimoField;

    private CartaPorteMercanciasTransporteAereo transporteAereoField;

    private CartaPorteMercanciasTransporteFerroviario transporteFerroviarioField;

    private decimal pesoBrutoTotalField;

    private string unidadPesoField;

    private decimal pesoNetoTotalField;

    private bool pesoNetoTotalFieldSpecified;

    private int numTotalMercanciasField;

    private decimal cargoPorTasacionField;

    private bool cargoPorTasacionFieldSpecified;

    private string logisticaInversaRecoleccionDevolucionField;

    private bool logisticaInversaRecoleccionDevolucionFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mercancia")]
    public CartaPorteMercanciasMercancia[] Mercancia
    {
        get
        {
            return this.mercanciaField;
        }
        set
        {
            this.mercanciaField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercanciasAutotransporte Autotransporte
    {
        get
        {
            return this.autotransporteField;
        }
        set
        {
            this.autotransporteField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercanciasTransporteMaritimo TransporteMaritimo
    {
        get
        {
            return this.transporteMaritimoField;
        }
        set
        {
            this.transporteMaritimoField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercanciasTransporteAereo TransporteAereo
    {
        get
        {
            return this.transporteAereoField;
        }
        set
        {
            this.transporteAereoField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercanciasTransporteFerroviario TransporteFerroviario
    {
        get
        {
            return this.transporteFerroviarioField;
        }
        set
        {
            this.transporteFerroviarioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoBrutoTotal
    {
        get
        {
            return this.pesoBrutoTotalField;
        }
        set
        {
            this.pesoBrutoTotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UnidadPeso
    {
        get
        {
            return this.unidadPesoField;
        }
        set
        {
            this.unidadPesoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoNetoTotal
    {
        get
        {
            return this.pesoNetoTotalField;
        }
        set
        {
            pesoNetoTotalFieldSpecified = true;
            this.pesoNetoTotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PesoNetoTotalSpecified
    {
        get
        {
            return this.pesoNetoTotalFieldSpecified;
        }
        set
        {
            this.pesoNetoTotalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NumTotalMercancias
    {
        get
        {
            return this.numTotalMercanciasField;
        }
        set
        {
            this.numTotalMercanciasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal CargoPorTasacion
    {
        get
        {
            return this.cargoPorTasacionField;
        }
        set
        {
            cargoPorTasacionFieldSpecified = true;
            this.cargoPorTasacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CargoPorTasacionSpecified
    {
        get
        {
            return this.cargoPorTasacionFieldSpecified;
        }
        set
        {
            this.cargoPorTasacionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LogisticaInversaRecoleccionDevolucion
    {
        get
        {
            return this.logisticaInversaRecoleccionDevolucionField;
        }
        set
        {
            logisticaInversaRecoleccionDevolucionFieldSpecified = true;
            this.logisticaInversaRecoleccionDevolucionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LogisticaInversaRecoleccionDevolucionSpecified
    {
        get
        {
            return this.logisticaInversaRecoleccionDevolucionFieldSpecified;
        }
        set
        {
            this.logisticaInversaRecoleccionDevolucionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasMercancia
{

    private CartaPorteMercanciasMercanciaDocumentacionAduanera[] documentacionAduaneraField;

    private CartaPorteMercanciasMercanciaGuiasIdentificacion[] guiasIdentificacionField;

    private CartaPorteMercanciasMercanciaCantidadTransporta[] cantidadTransportaField;

    private CartaPorteMercanciasMercanciaDetalleMercancia detalleMercanciaField;

    private string bienesTranspField;

    private string claveSTCCField;

    private string descripcionField;

    private decimal cantidadField;

    private string claveUnidadField;

    private string unidadField;

    private string dimensionesField;

    private string materialPeligrosoField;

    private bool materialPeligrosoFieldSpecified;

    private string cveMaterialPeligrosoField;

    private bool cveMaterialPeligrosoFieldSpecified;

    private string embalajeField;

    private bool embalajeFieldSpecified;

    private string descripEmbalajeField;

    private string sectorCOFEPRISField;

    private bool sectorCOFEPRISFieldSpecified;

    private string nombreIngredienteActivoField;

    private string nomQuimicoField;

    private string denominacionGenericaProdField;

    private string denominacionDistintivaProdField;

    private string fabricanteField;

    private System.DateTime fechaCaducidadField;

    private bool fechaCaducidadFieldSpecified;

    private string loteMedicamentoField;

    private string formaFarmaceuticaField;

    private bool formaFarmaceuticaFieldSpecified;

    private string condicionesEspTranspField;

    private bool condicionesEspTranspFieldSpecified;

    private string registroSanitarioFolioAutorizacionField;

    private string permisoImportacionField;

    private string folioImpoVUCEMField;

    private string numCASField;

    private string razonSocialEmpImpField;

    private string numRegSanPlagCOFEPRISField;

    private string datosFabricanteField;

    private string datosFormuladorField;

    private string datosMaquiladorField;

    private string usoAutorizadoField;

    private decimal pesoEnKgField;

    private decimal valorMercanciaField;

    private bool valorMercanciaFieldSpecified;

    private string monedaField;

    private bool monedaFieldSpecified;

    private string fraccionArancelariaField;

    private bool fraccionArancelariaFieldSpecified;

    private string uUIDComercioExtField;

    private string tipoMateriaField;

    private bool tipoMateriaFieldSpecified;

    private string descripcionMateriaField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentacionAduanera")]
    public CartaPorteMercanciasMercanciaDocumentacionAduanera[] DocumentacionAduanera
    {
        get
        {
            return this.documentacionAduaneraField;
        }
        set
        {
            this.documentacionAduaneraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GuiasIdentificacion")]
    public CartaPorteMercanciasMercanciaGuiasIdentificacion[] GuiasIdentificacion
    {
        get
        {
            return this.guiasIdentificacionField;
        }
        set
        {
            this.guiasIdentificacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CantidadTransporta")]
    public CartaPorteMercanciasMercanciaCantidadTransporta[] CantidadTransporta
    {
        get
        {
            return this.cantidadTransportaField;
        }
        set
        {
            this.cantidadTransportaField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercanciasMercanciaDetalleMercancia DetalleMercancia
    {
        get
        {
            return this.detalleMercanciaField;
        }
        set
        {
            this.detalleMercanciaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BienesTransp
    {
        get
        {
            return this.bienesTranspField;
        }
        set
        {
            this.bienesTranspField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClaveSTCC
    {
        get
        {
            return this.claveSTCCField;
        }
        set
        {
            this.claveSTCCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Descripcion
    {
        get
        {
            return this.descripcionField;
        }
        set
        {
            this.descripcionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClaveUnidad
    {
        get
        {
            return this.claveUnidadField;
        }
        set
        {
            this.claveUnidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unidad
    {
        get
        {
            return this.unidadField;
        }
        set
        {
            this.unidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Dimensiones
    {
        get
        {
            return this.dimensionesField;
        }
        set
        {
            this.dimensionesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialPeligroso
    {
        get
        {
            return this.materialPeligrosoField;
        }
        set
        {
            materialPeligrosoFieldSpecified = true;
            this.materialPeligrosoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaterialPeligrosoSpecified
    {
        get
        {
            return this.materialPeligrosoFieldSpecified;
        }
        set
        {
            this.materialPeligrosoFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CveMaterialPeligroso
    {
        get
        {
            return this.cveMaterialPeligrosoField;
        }
        set
        {
            cveMaterialPeligrosoFieldSpecified = true;
            this.cveMaterialPeligrosoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CveMaterialPeligrosoSpecified
    {
        get
        {
            return this.cveMaterialPeligrosoFieldSpecified;
        }
        set
        {
            this.cveMaterialPeligrosoFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Embalaje
    {
        get
        {
            return this.embalajeField;
        }
        set
        {
            embalajeFieldSpecified = true;
            this.embalajeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EmbalajeSpecified
    {
        get
        {
            return this.embalajeFieldSpecified;
        }
        set
        {
            this.embalajeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescripEmbalaje
    {
        get
        {
            return this.descripEmbalajeField;
        }
        set
        {
            this.descripEmbalajeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SectorCOFEPRIS
    {
        get
        {
            return this.sectorCOFEPRISField;
        }
        set
        {
            sectorCOFEPRISFieldSpecified = true;
            this.sectorCOFEPRISField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SectorCOFEPRISSpecified
    {
        get
        {
            return this.sectorCOFEPRISFieldSpecified;
        }
        set
        {
            this.sectorCOFEPRISFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreIngredienteActivo
    {
        get
        {
            return this.nombreIngredienteActivoField;
        }
        set
        {
            this.nombreIngredienteActivoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NomQuimico
    {
        get
        {
            return this.nomQuimicoField;
        }
        set
        {
            this.nomQuimicoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DenominacionGenericaProd
    {
        get
        {
            return this.denominacionGenericaProdField;
        }
        set
        {
            this.denominacionGenericaProdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DenominacionDistintivaProd
    {
        get
        {
            return this.denominacionDistintivaProdField;
        }
        set
        {
            this.denominacionDistintivaProdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Fabricante
    {
        get
        {
            return this.fabricanteField;
        }
        set
        {
            this.fabricanteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime FechaCaducidad
    {
        get
        {
            return this.fechaCaducidadField;
        }
        set
        {
            fechaCaducidadFieldSpecified = true;
            this.fechaCaducidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FechaCaducidadSpecified
    {
        get
        {
            return this.fechaCaducidadFieldSpecified;
        }
        set
        {
            this.fechaCaducidadFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LoteMedicamento
    {
        get
        {
            return this.loteMedicamentoField;
        }
        set
        {
            this.loteMedicamentoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FormaFarmaceutica
    {
        get
        {
            return this.formaFarmaceuticaField;
        }
        set
        {
            formaFarmaceuticaFieldSpecified = true;
            this.formaFarmaceuticaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FormaFarmaceuticaSpecified
    {
        get
        {
            return this.formaFarmaceuticaFieldSpecified;
        }
        set
        {
            this.formaFarmaceuticaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CondicionesEspTransp
    {
        get
        {
            return this.condicionesEspTranspField;
        }
        set
        {
            condicionesEspTranspFieldSpecified = true;
            this.condicionesEspTranspField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CondicionesEspTranspSpecified
    {
        get
        {
            return this.condicionesEspTranspFieldSpecified;
        }
        set
        {
            this.condicionesEspTranspFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RegistroSanitarioFolioAutorizacion
    {
        get
        {
            return this.registroSanitarioFolioAutorizacionField;
        }
        set
        {
            this.registroSanitarioFolioAutorizacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PermisoImportacion
    {
        get
        {
            return this.permisoImportacionField;
        }
        set
        {
            this.permisoImportacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FolioImpoVUCEM
    {
        get
        {
            return this.folioImpoVUCEMField;
        }
        set
        {
            this.folioImpoVUCEMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumCAS
    {
        get
        {
            return this.numCASField;
        }
        set
        {
            this.numCASField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RazonSocialEmpImp
    {
        get
        {
            return this.razonSocialEmpImpField;
        }
        set
        {
            this.razonSocialEmpImpField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumRegSanPlagCOFEPRIS
    {
        get
        {
            return this.numRegSanPlagCOFEPRISField;
        }
        set
        {
            this.numRegSanPlagCOFEPRISField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DatosFabricante
    {
        get
        {
            return this.datosFabricanteField;
        }
        set
        {
            this.datosFabricanteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DatosFormulador
    {
        get
        {
            return this.datosFormuladorField;
        }
        set
        {
            this.datosFormuladorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DatosMaquilador
    {
        get
        {
            return this.datosMaquiladorField;
        }
        set
        {
            this.datosMaquiladorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UsoAutorizado
    {
        get
        {
            return this.usoAutorizadoField;
        }
        set
        {
            this.usoAutorizadoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoEnKg
    {
        get
        {
            return this.pesoEnKgField;
        }
        set
        {
            this.pesoEnKgField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ValorMercancia
    {
        get
        {
            return this.valorMercanciaField;
        }
        set
        {
            valorMercanciaFieldSpecified = true;
            this.valorMercanciaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValorMercanciaSpecified
    {
        get
        {
            return this.valorMercanciaFieldSpecified;
        }
        set
        {
            this.valorMercanciaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Moneda
    {
        get
        {
            return this.monedaField;
        }
        set
        {
            monedaFieldSpecified = true;
            this.monedaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MonedaSpecified
    {
        get
        {
            return this.monedaFieldSpecified;
        }
        set
        {
            this.monedaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FraccionArancelaria
    {
        get
        {
            return this.fraccionArancelariaField;
        }
        set
        {
            fraccionArancelariaFieldSpecified = true;
            this.fraccionArancelariaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FraccionArancelariaSpecified
    {
        get
        {
            return this.fraccionArancelariaFieldSpecified;
        }
        set
        {
            this.fraccionArancelariaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UUIDComercioExt
    {
        get
        {
            return this.uUIDComercioExtField;
        }
        set
        {
            this.uUIDComercioExtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoMateria
    {
        get
        {
            return this.tipoMateriaField;
        }
        set
        {
            tipoMateriaFieldSpecified = true;
            this.tipoMateriaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TipoMateriaSpecified
    {
        get
        {
            return this.tipoMateriaFieldSpecified;
        }
        set
        {
            this.tipoMateriaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescripcionMateria
    {
        get
        {
            return this.descripcionMateriaField;
        }
        set
        {
            this.descripcionMateriaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasMercanciaDocumentacionAduanera
{

    private string tipoDocumentoField;

    private string numPedimentoField;

    private string identDocAduaneroField;

    private string rFCImpoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoDocumento
    {
        get
        {
            return this.tipoDocumentoField;
        }
        set
        {
            this.tipoDocumentoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPedimento
    {
        get
        {
            return this.numPedimentoField;
        }
        set
        {
            this.numPedimentoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IdentDocAduanero
    {
        get
        {
            return this.identDocAduaneroField;
        }
        set
        {
            this.identDocAduaneroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RFCImpo
    {
        get
        {
            return this.rFCImpoField;
        }
        set
        {
            this.rFCImpoField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasMercanciaGuiasIdentificacion
{

    private string numeroGuiaIdentificacionField;

    private string descripGuiaIdentificacionField;

    private decimal pesoGuiaIdentificacionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroGuiaIdentificacion
    {
        get
        {
            return this.numeroGuiaIdentificacionField;
        }
        set
        {
            this.numeroGuiaIdentificacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DescripGuiaIdentificacion
    {
        get
        {
            return this.descripGuiaIdentificacionField;
        }
        set
        {
            this.descripGuiaIdentificacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoGuiaIdentificacion
    {
        get
        {
            return this.pesoGuiaIdentificacionField;
        }
        set
        {
            this.pesoGuiaIdentificacionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasMercanciaCantidadTransporta
{

    private decimal cantidadField;

    private string iDOrigenField;

    private string iDDestinoField;

    private string cvesTransporteField;

    private bool cvesTransporteFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Cantidad
    {
        get
        {
            return this.cantidadField;
        }
        set
        {
            this.cantidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IDOrigen
    {
        get
        {
            return this.iDOrigenField;
        }
        set
        {
            this.iDOrigenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IDDestino
    {
        get
        {
            return this.iDDestinoField;
        }
        set
        {
            this.iDDestinoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CvesTransporte
    {
        get
        {
            return this.cvesTransporteField;
        }
        set
        {
            cvesTransporteFieldSpecified = true;
            this.cvesTransporteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CvesTransporteSpecified
    {
        get
        {
            return this.cvesTransporteFieldSpecified;
        }
        set
        {
            this.cvesTransporteFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasMercanciaDetalleMercancia
{

    private string unidadPesoMercField;

    private decimal pesoBrutoField;

    private decimal pesoNetoField;

    private decimal pesoTaraField;

    private int numPiezasField;

    private bool numPiezasFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UnidadPesoMerc
    {
        get
        {
            return this.unidadPesoMercField;
        }
        set
        {
            this.unidadPesoMercField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoBruto
    {
        get
        {
            return this.pesoBrutoField;
        }
        set
        {
            this.pesoBrutoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoNeto
    {
        get
        {
            return this.pesoNetoField;
        }
        set
        {
            this.pesoNetoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoTara
    {
        get
        {
            return this.pesoTaraField;
        }
        set
        {
            this.pesoTaraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NumPiezas
    {
        get
        {
            return this.numPiezasField;
        }
        set
        {
            numPiezasFieldSpecified = true;
            this.numPiezasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumPiezasSpecified
    {
        get
        {
            return this.numPiezasFieldSpecified;
        }
        set
        {
            this.numPiezasFieldSpecified = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasAutotransporte
{

    private CartaPorteMercanciasAutotransporteIdentificacionVehicular identificacionVehicularField;

    private CartaPorteMercanciasAutotransporteSeguros segurosField;

    private CartaPorteMercanciasAutotransporteRemolque[] remolquesField;

    private string permSCTField;

    private string numPermisoSCTField;

    /// <remarks/>
    public CartaPorteMercanciasAutotransporteIdentificacionVehicular IdentificacionVehicular
    {
        get
        {
            return this.identificacionVehicularField;
        }
        set
        {
            this.identificacionVehicularField = value;
        }
    }

    /// <remarks/>
    public CartaPorteMercanciasAutotransporteSeguros Seguros
    {
        get
        {
            return this.segurosField;
        }
        set
        {
            this.segurosField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Remolque", IsNullable = false)]
    public CartaPorteMercanciasAutotransporteRemolque[] Remolques
    {
        get
        {
            return this.remolquesField;
        }
        set
        {
            this.remolquesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PermSCT
    {
        get
        {
            return this.permSCTField;
        }
        set
        {
            this.permSCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPermisoSCT
    {
        get
        {
            return this.numPermisoSCTField;
        }
        set
        {
            this.numPermisoSCTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasAutotransporteIdentificacionVehicular
{

    private string configVehicularField;

    private decimal pesoBrutoVehicularField;

    private string placaVMField;

    private int anioModeloVMField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConfigVehicular
    {
        get
        {
            return this.configVehicularField;
        }
        set
        {
            this.configVehicularField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoBrutoVehicular
    {
        get
        {
            return this.pesoBrutoVehicularField;
        }
        set
        {
            this.pesoBrutoVehicularField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PlacaVM
    {
        get
        {
            return this.placaVMField;
        }
        set
        {
            this.placaVMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int AnioModeloVM
    {
        get
        {
            return this.anioModeloVMField;
        }
        set
        {
            this.anioModeloVMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasAutotransporteSeguros
{

    private string aseguraRespCivilField;

    private string polizaRespCivilField;

    private string aseguraMedAmbienteField;

    private string polizaMedAmbienteField;

    private string aseguraCargaField;

    private string polizaCargaField;

    private decimal primaSeguroField;

    private bool primaSeguroFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AseguraRespCivil
    {
        get
        {
            return this.aseguraRespCivilField;
        }
        set
        {
            this.aseguraRespCivilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PolizaRespCivil
    {
        get
        {
            return this.polizaRespCivilField;
        }
        set
        {
            this.polizaRespCivilField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AseguraMedAmbiente
    {
        get
        {
            return this.aseguraMedAmbienteField;
        }
        set
        {
            this.aseguraMedAmbienteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PolizaMedAmbiente
    {
        get
        {
            return this.polizaMedAmbienteField;
        }
        set
        {
            this.polizaMedAmbienteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AseguraCarga
    {
        get
        {
            return this.aseguraCargaField;
        }
        set
        {
            this.aseguraCargaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PolizaCarga
    {
        get
        {
            return this.polizaCargaField;
        }
        set
        {
            this.polizaCargaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PrimaSeguro
    {
        get
        {
            return this.primaSeguroField;
        }
        set
        {
            primaSeguroFieldSpecified = true;
            this.primaSeguroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrimaSeguroSpecified
    {
        get
        {
            return this.primaSeguroFieldSpecified;
        }
        set
        {
            this.primaSeguroFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasAutotransporteRemolque
{

    private string subTipoRemField;

    private string placaField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SubTipoRem
    {
        get
        {
            return this.subTipoRemField;
        }
        set
        {
            this.subTipoRemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Placa
    {
        get
        {
            return this.placaField;
        }
        set
        {
            this.placaField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteMaritimo
{

    private CartaPorteMercanciasTransporteMaritimoContenedor[] contenedorField;

    private CartaPorteMercanciasTransporteMaritimoRemolqueCCP[] remolquesCCPField;

    private string permSCTField;

    private bool permSCTFieldSpecified;

    private string numPermisoSCTField;

    private string nombreAsegField;

    private string numPolizaSeguroField;

    private string tipoEmbarcacionField;

    private string matriculaField;

    private string numeroOMIField;

    private int anioEmbarcacionField;

    private bool anioEmbarcacionFieldSpecified;

    private string nombreEmbarcField;

    private string nacionalidadEmbarcField;

    private decimal unidadesDeArqBrutoField;

    private string tipoCargaField;

    private decimal esloraField;

    private bool esloraFieldSpecified;

    private decimal mangaField;

    private bool mangaFieldSpecified;

    private decimal caladoField;

    private bool caladoFieldSpecified;

    private decimal puntalField;

    private bool puntalFieldSpecified;

    private string lineaNavieraField;

    private string nombreAgenteNavieroField;

    private string numAutorizacionNavieroField;

    private string numViajeField;

    private string numConocEmbarcField;

    private string permisoTempNavegacionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contenedor")]
    public CartaPorteMercanciasTransporteMaritimoContenedor[] Contenedor
    {
        get
        {
            return this.contenedorField;
        }
        set
        {
            this.contenedorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RemolqueCCP", IsNullable = false)]
    public CartaPorteMercanciasTransporteMaritimoRemolqueCCP[] RemolquesCCP
    {
        get
        {
            return this.remolquesCCPField;
        }
        set
        {
            this.remolquesCCPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PermSCT
    {
        get
        {
            return this.permSCTField;
        }
        set
        {
            permSCTFieldSpecified = true;
            this.permSCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PermSCTSpecified
    {
        get
        {
            return this.permSCTFieldSpecified;
        }
        set
        {
            this.permSCTFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPermisoSCT
    {
        get
        {
            return this.numPermisoSCTField;
        }
        set
        {
            this.numPermisoSCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreAseg
    {
        get
        {
            return this.nombreAsegField;
        }
        set
        {
            this.nombreAsegField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPolizaSeguro
    {
        get
        {
            return this.numPolizaSeguroField;
        }
        set
        {
            this.numPolizaSeguroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoEmbarcacion
    {
        get
        {
            return this.tipoEmbarcacionField;
        }
        set
        {
            this.tipoEmbarcacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Matricula
    {
        get
        {
            return this.matriculaField;
        }
        set
        {
            this.matriculaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroOMI
    {
        get
        {
            return this.numeroOMIField;
        }
        set
        {
            this.numeroOMIField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int AnioEmbarcacion
    {
        get
        {
            return this.anioEmbarcacionField;
        }
        set
        {
            anioEmbarcacionFieldSpecified = true;
            this.anioEmbarcacionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnioEmbarcacionSpecified
    {
        get
        {
            return this.anioEmbarcacionFieldSpecified;
        }
        set
        {
            this.anioEmbarcacionFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreEmbarc
    {
        get
        {
            return this.nombreEmbarcField;
        }
        set
        {
            this.nombreEmbarcField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NacionalidadEmbarc
    {
        get
        {
            return this.nacionalidadEmbarcField;
        }
        set
        {
            this.nacionalidadEmbarcField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal UnidadesDeArqBruto
    {
        get
        {
            return this.unidadesDeArqBrutoField;
        }
        set
        {
            this.unidadesDeArqBrutoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoCarga
    {
        get
        {
            return this.tipoCargaField;
        }
        set
        {
            this.tipoCargaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Eslora
    {
        get
        {
            return this.esloraField;
        }
        set
        {
            esloraFieldSpecified = true;
            this.esloraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EsloraSpecified
    {
        get
        {
            return this.esloraFieldSpecified;
        }
        set
        {
            this.esloraFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Manga
    {
        get
        {
            return this.mangaField;
        }
        set
        {
            mangaFieldSpecified = true;
            this.mangaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MangaSpecified
    {
        get
        {
            return this.mangaFieldSpecified;
        }
        set
        {
            this.mangaFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Calado
    {
        get
        {
            return this.caladoField;
        }
        set
        {
            caladoFieldSpecified = true;
            this.caladoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CaladoSpecified
    {
        get
        {
            return this.caladoFieldSpecified;
        }
        set
        {
            this.caladoFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Puntal
    {
        get
        {
            return this.puntalField;
        }
        set
        {
            puntalFieldSpecified = true;
            this.puntalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PuntalSpecified
    {
        get
        {
            return this.puntalFieldSpecified;
        }
        set
        {
            this.puntalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LineaNaviera
    {
        get
        {
            return this.lineaNavieraField;
        }
        set
        {
            this.lineaNavieraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreAgenteNaviero
    {
        get
        {
            return this.nombreAgenteNavieroField;
        }
        set
        {
            this.nombreAgenteNavieroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumAutorizacionNaviero
    {
        get
        {
            return this.numAutorizacionNavieroField;
        }
        set
        {
            this.numAutorizacionNavieroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumViaje
    {
        get
        {
            return this.numViajeField;
        }
        set
        {
            this.numViajeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumConocEmbarc
    {
        get
        {
            return this.numConocEmbarcField;
        }
        set
        {
            this.numConocEmbarcField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PermisoTempNavegacion
    {
        get
        {
            return this.permisoTempNavegacionField;
        }
        set
        {
            this.permisoTempNavegacionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteMaritimoContenedor
{

    private string tipoContenedorField;

    private string matriculaContenedorField;

    private string numPrecintoField;

    private string idCCPRelacionadoField;

    private string placaVMCCPField;

    private System.DateTime fechaCertificacionCCPField;

    private bool fechaCertificacionCCPFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoContenedor
    {
        get
        {
            return this.tipoContenedorField;
        }
        set
        {
            this.tipoContenedorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MatriculaContenedor
    {
        get
        {
            return this.matriculaContenedorField;
        }
        set
        {
            this.matriculaContenedorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPrecinto
    {
        get
        {
            return this.numPrecintoField;
        }
        set
        {
            this.numPrecintoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IdCCPRelacionado
    {
        get
        {
            return this.idCCPRelacionadoField;
        }
        set
        {
            this.idCCPRelacionadoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PlacaVMCCP
    {
        get
        {
            return this.placaVMCCPField;
        }
        set
        {
            this.placaVMCCPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime FechaCertificacionCCP
    {
        get
        {
            return this.fechaCertificacionCCPField;
        }
        set
        {
            fechaCertificacionCCPFieldSpecified = true;
            this.fechaCertificacionCCPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FechaCertificacionCCPSpecified
    {
        get
        {
            return this.fechaCertificacionCCPFieldSpecified;
        }
        set
        {
            this.fechaCertificacionCCPFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteMaritimoRemolqueCCP
{

    private string subTipoRemCCPField;

    private string placaCCPField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SubTipoRemCCP
    {
        get
        {
            return this.subTipoRemCCPField;
        }
        set
        {
            this.subTipoRemCCPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PlacaCCP
    {
        get
        {
            return this.placaCCPField;
        }
        set
        {
            this.placaCCPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteAereo
{

    private string permSCTField;

    private string numPermisoSCTField;

    private string matriculaAeronaveField;

    private string nombreAsegField;

    private string numPolizaSeguroField;

    private string numeroGuiaField;

    private string lugarContratoField;

    private string codigoTransportistaField;

    private string rFCEmbarcadorField;

    private string numRegIdTribEmbarcField;

    private string residenciaFiscalEmbarcField;

    private bool residenciaFiscalEmbarcFieldSpecified;

    private string nombreEmbarcadorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PermSCT
    {
        get
        {
            return this.permSCTField;
        }
        set
        {
            this.permSCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPermisoSCT
    {
        get
        {
            return this.numPermisoSCTField;
        }
        set
        {
            this.numPermisoSCTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MatriculaAeronave
    {
        get
        {
            return this.matriculaAeronaveField;
        }
        set
        {
            this.matriculaAeronaveField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreAseg
    {
        get
        {
            return this.nombreAsegField;
        }
        set
        {
            this.nombreAsegField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPolizaSeguro
    {
        get
        {
            return this.numPolizaSeguroField;
        }
        set
        {
            this.numPolizaSeguroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroGuia
    {
        get
        {
            return this.numeroGuiaField;
        }
        set
        {
            this.numeroGuiaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LugarContrato
    {
        get
        {
            return this.lugarContratoField;
        }
        set
        {
            this.lugarContratoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CodigoTransportista
    {
        get
        {
            return this.codigoTransportistaField;
        }
        set
        {
            this.codigoTransportistaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RFCEmbarcador
    {
        get
        {
            return this.rFCEmbarcadorField;
        }
        set
        {
            this.rFCEmbarcadorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumRegIdTribEmbarc
    {
        get
        {
            return this.numRegIdTribEmbarcField;
        }
        set
        {
            this.numRegIdTribEmbarcField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResidenciaFiscalEmbarc
    {
        get
        {
            return this.residenciaFiscalEmbarcField;
        }
        set
        {
            residenciaFiscalEmbarcFieldSpecified = true;
            this.residenciaFiscalEmbarcField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResidenciaFiscalEmbarcSpecified
    {
        get
        {
            return this.residenciaFiscalEmbarcFieldSpecified;
        }
        set
        {
            this.residenciaFiscalEmbarcFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreEmbarcador
    {
        get
        {
            return this.nombreEmbarcadorField;
        }
        set
        {
            this.nombreEmbarcadorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteFerroviario
{

    private CartaPorteMercanciasTransporteFerroviarioDerechosDePaso[] derechosDePasoField;

    private CartaPorteMercanciasTransporteFerroviarioCarro[] carroField;

    private string tipoDeServicioField;

    private string tipoDeTraficoField;

    private string nombreAsegField;

    private string numPolizaSeguroField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerechosDePaso")]
    public CartaPorteMercanciasTransporteFerroviarioDerechosDePaso[] DerechosDePaso
    {
        get
        {
            return this.derechosDePasoField;
        }
        set
        {
            this.derechosDePasoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Carro")]
    public CartaPorteMercanciasTransporteFerroviarioCarro[] Carro
    {
        get
        {
            return this.carroField;
        }
        set
        {
            this.carroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoDeServicio
    {
        get
        {
            return this.tipoDeServicioField;
        }
        set
        {
            this.tipoDeServicioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoDeTrafico
    {
        get
        {
            return this.tipoDeTraficoField;
        }
        set
        {
            this.tipoDeTraficoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreAseg
    {
        get
        {
            return this.nombreAsegField;
        }
        set
        {
            this.nombreAsegField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumPolizaSeguro
    {
        get
        {
            return this.numPolizaSeguroField;
        }
        set
        {
            this.numPolizaSeguroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteFerroviarioDerechosDePaso
{

    private string tipoDerechoDePasoField;

    private decimal kilometrajePagadoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoDerechoDePaso
    {
        get
        {
            return this.tipoDerechoDePasoField;
        }
        set
        {
            this.tipoDerechoDePasoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal KilometrajePagado
    {
        get
        {
            return this.kilometrajePagadoField;
        }
        set
        {
            this.kilometrajePagadoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteFerroviarioCarro
{

    private CartaPorteMercanciasTransporteFerroviarioCarroContenedor[] contenedorField;

    private string tipoCarroField;

    private string matriculaCarroField;

    private string guiaCarroField;

    private decimal toneladasNetasCarroField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Contenedor")]
    public CartaPorteMercanciasTransporteFerroviarioCarroContenedor[] Contenedor
    {
        get
        {
            return this.contenedorField;
        }
        set
        {
            this.contenedorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoCarro
    {
        get
        {
            return this.tipoCarroField;
        }
        set
        {
            this.tipoCarroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MatriculaCarro
    {
        get
        {
            return this.matriculaCarroField;
        }
        set
        {
            this.matriculaCarroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GuiaCarro
    {
        get
        {
            return this.guiaCarroField;
        }
        set
        {
            this.guiaCarroField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal ToneladasNetasCarro
    {
        get
        {
            return this.toneladasNetasCarroField;
        }
        set
        {
            this.toneladasNetasCarroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteMercanciasTransporteFerroviarioCarroContenedor
{

    private string tipoContenedorField;

    private decimal pesoContenedorVacioField;

    private decimal pesoNetoMercanciaField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoContenedor
    {
        get
        {
            return this.tipoContenedorField;
        }
        set
        {
            this.tipoContenedorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoContenedorVacio
    {
        get
        {
            return this.pesoContenedorVacioField;
        }
        set
        {
            this.pesoContenedorVacioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal PesoNetoMercancia
    {
        get
        {
            return this.pesoNetoMercanciaField;
        }
        set
        {
            this.pesoNetoMercanciaField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteTiposFigura
{

    private CartaPorteTiposFiguraPartesTransporte[] partesTransporteField;

    private CartaPorteTiposFiguraDomicilio domicilioField;

    private string tipoFiguraField;

    private string rFCFiguraField;

    private string numLicenciaField;

    private string nombreFiguraField;

    private string numRegIdTribFiguraField;

    private string residenciaFiscalFiguraField;

    private bool residenciaFiscalFiguraFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PartesTransporte")]
    public CartaPorteTiposFiguraPartesTransporte[] PartesTransporte
    {
        get
        {
            return this.partesTransporteField;
        }
        set
        {
            this.partesTransporteField = value;
        }
    }

    /// <remarks/>
    public CartaPorteTiposFiguraDomicilio Domicilio
    {
        get
        {
            return this.domicilioField;
        }
        set
        {
            this.domicilioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TipoFigura
    {
        get
        {
            return this.tipoFiguraField;
        }
        set
        {
            this.tipoFiguraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RFCFigura
    {
        get
        {
            return this.rFCFiguraField;
        }
        set
        {
            this.rFCFiguraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumLicencia
    {
        get
        {
            return this.numLicenciaField;
        }
        set
        {
            this.numLicenciaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NombreFigura
    {
        get
        {
            return this.nombreFiguraField;
        }
        set
        {
            this.nombreFiguraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumRegIdTribFigura
    {
        get
        {
            return this.numRegIdTribFiguraField;
        }
        set
        {
            this.numRegIdTribFiguraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResidenciaFiscalFigura
    {
        get
        {
            return this.residenciaFiscalFiguraField;
        }
        set
        {
            residenciaFiscalFiguraFieldSpecified = true;
            this.residenciaFiscalFiguraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResidenciaFiscalFiguraSpecified
    {
        get
        {
            return this.residenciaFiscalFiguraFieldSpecified;
        }
        set
        {
            this.residenciaFiscalFiguraFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteTiposFiguraPartesTransporte
{

    private string parteTransporteField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParteTransporte
    {
        get
        {
            return this.parteTransporteField;
        }
        set
        {
            this.parteTransporteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/CartaPorte30")]
public partial class CartaPorteTiposFiguraDomicilio
{

    private string calleField;

    private string numeroExteriorField;

    private string numeroInteriorField;

    private string coloniaField;

    private string localidadField;

    private string referenciaField;

    private string municipioField;

    private string estadoField;

    private string paisField;

    private string codigoPostalField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Calle
    {
        get
        {
            return this.calleField;
        }
        set
        {
            this.calleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroExterior
    {
        get
        {
            return this.numeroExteriorField;
        }
        set
        {
            this.numeroExteriorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NumeroInterior
    {
        get
        {
            return this.numeroInteriorField;
        }
        set
        {
            this.numeroInteriorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Colonia
    {
        get
        {
            return this.coloniaField;
        }
        set
        {
            this.coloniaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Localidad
    {
        get
        {
            return this.localidadField;
        }
        set
        {
            this.localidadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Referencia
    {
        get
        {
            return this.referenciaField;
        }
        set
        {
            this.referenciaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Municipio
    {
        get
        {
            return this.municipioField;
        }
        set
        {
            this.municipioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Estado
    {
        get
        {
            return this.estadoField;
        }
        set
        {
            this.estadoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Pais
    {
        get
        {
            return this.paisField;
        }
        set
        {
            this.paisField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CodigoPostal
    {
        get
        {
            return this.codigoPostalField;
        }
        set
        {
            this.codigoPostalField = value;
        }
    }
}







